language: node_js   # 声明构建语言环境

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
  email: false

node_js:
  - "8"

cache:
  directories:
    - node_modules

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: BetaMee/oakserver
    bucket: s3-oakserver-us-east
    region: us-east-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: s3-oakserver-us-east
    key: latest.zip
    bundle_type: zip
    application: CodoDeployAppFromGithub
    deployment_group: CodoDeployAppFromGithubGroup
    region: us-east-2
    on: *2

script:
  - npm run build
  - zip -r latest ./dist/*
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip