# 声明构建语言环境
language: node_js

# 每次构建的时候是否通知
notifications:
  email: false # 关闭邮件通知
  slack: loveoak:$SLACK_LOVEOAK_CHNEEL # 开启slack通知

# nodejs语言版本
node_js:
  - "8"

# 缓存
cache: yarn

# 使用docker必须的配置
sudo: required

# 使用docker
services:
  - docker

# 执行测试脚本，未开启
script:


# 部署
deploy:
  provider: elasticbeanstalk # 部署到AWS elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY #IAM ACCESS_KEY，在Travis上设置
  secret_access_key:             #IAM SECRET_KEY
    secure: "$AWS_SECRET_KEY"
  region: "ap-northeast-1" # elasticbeanstalk上的地区
  app: "oakserver" # app名字
  env: "oakserver-dev" # 部署的环境
  bucket_name: "elasticbeanstalk-ap-northeast-1-459948791791"   # S3的名字，和elasticbeanstalk绑定，用于存储docker文件
  on:
    branch: master # 值部署主分支
  skip_cleanup: true

# 部署之后
after_deploy:
  - echo "done deploying"