language: node_js   # 声明构建语言环境

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
  email: false

node_js:
  - "8"

cache:
  directories:
    - node_modules

sudo: required

services:
  - docker


script:
  - npm install #安装依赖
  - npm run build # 打包dist文件

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: #IAM密钥
    secure: "$AWS_SECRET_KEY"
  region: "ap-northeast-1"  
  app: "oakserver"
  env: "oakserver-dev"
  bucket_name: "elasticbeanstalk-ap-northeast-1-459948791791"
  on:
    branch: master

after_deploy:
  - echo "done deploying"