branch-defaults:
  master:
    environment: oakserver-pro
    group_suffix: null
global:
  application_name: oakserver
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 17.09.1-ce
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
